# Housing Market

### Introduction:

This time we will create our own dataset with fictional numbers to describe a house market. As we are going to create random data don't try to reason of the numbers.

### Step 1. Import the necessary libraries

In [24]:
import pandas as pd
import numpy as np

### Step 2. Create 3 differents Series, each of length 100, as follows:
1. The first a random number from 1 to 4
2. The second a random number from 1 to 3
3. The third a random number from 10,000 to 30,000

In [25]:
s1= pd.Series(np.random.randint(1,5,100))
s2=pd.Series(np.random.randint(1,4,100))
s3=pd.Series(np.random.randint(10000,30000,100))
print(s1,s2,s3)

0     3
1     3
2     1
3     3
4     3
     ..
95    4
96    1
97    1
98    4
99    1
Length: 100, dtype: int64 0     2
1     3
2     2
3     1
4     1
     ..
95    1
96    3
97    1
98    3
99    2
Length: 100, dtype: int64 0     24391
1     28777
2     20517
3     18796
4     10438
      ...
95    21193
96    18630
97    12461
98    25499
99    10287
Length: 100, dtype: int64

### Step 3. Let's create a DataFrame by joinning the Series by column

In [26]:
housemkt = pd.concat([s1,s2,s3],axis=1)
housemkt.head()

   0  1      2
0  3  2  24391
1  3  3  28777
2  1  2  20517
3  3  1  18796
4  3  1  10438

### Step 4. Change the name of the columns to bedrs, bathrs, price_sqr_meter

In [27]:
housemkt.rename(columns={0:'bedrs',1:'bathrs',2:'price_sqr_meter'})

    bedrs  bathrs  price_sqr_meter
0       3       2            24391
1       3       3            28777
2       1       2            20517
3       3       1            18796
4       3       1            10438
..    ...     ...              ...
95      4       1            21193
96      1       3            18630
97      1       1            12461
98      4       3            25499
99      1       2            10287

[100 rows x 3 columns]

### Step 5. Create a one column DataFrame with the values of the 3 Series and assign it to 'bigcolumn'

In [28]:
bigcolumn = pd.concat([s1,s2,s3],axis=0)
bigcolumn = bigcolumn.to_frame()
print(type(bigcolumn))
bigcolumn

<class 'pandas.core.frame.DataFrame'>

        0
0       3
1       3
2       1
3       3
4       3
..    ...
95  21193
96  18630
97  12461
98  25499
99  10287

[300 rows x 1 columns]

### Step 6. Oops, it seems it is going only until index 99. Is it true?

In [29]:
len(bigcolumn)

300

### Step 7. Reindex the DataFrame so it goes from 0 to 299

In [30]:
col = bigcolumn.reset_index(drop=True)
col.tail()

         0
295  21193
296  18630
297  12461
298  25499
299  10287