1. Import the necessary libraries

In [17]:
import pandas as pd

 Step 2. Import the dataset from this address.

In [18]:
worldcup = pd.read_csv("/content/WorldCupMatches.csv")

Step 3. Count the total number of matches played in each World Cup year.

In [19]:
worldcup.groupby('Year')['Year'].count()

Year
1930.0    18
1934.0    17
1938.0    18
1950.0    22
1954.0    26
1958.0    35
1962.0    32
1966.0    32
1970.0    32
1974.0    38
1978.0    38
1982.0    52
1986.0    52
1990.0    52
1994.0    52
1998.0    64
2002.0    64
2006.0    64
2010.0    64
2014.0    80
Name: Year, dtype: int64

Step 4: Calculate the total attendance for each World Cup year.

In [20]:
worldcup.groupby('Year')['Attendance'].sum()

Year
1930.0     590549.0
1934.0     363000.0
1938.0     375700.0
1950.0    1045246.0
1954.0     768607.0
1958.0     819810.0
1962.0     893172.0
1966.0    1563135.0
1970.0    1603975.0
1974.0    1865753.0
1978.0    1545791.0
1982.0    2109723.0
1986.0    2394031.0
1990.0    2516215.0
1994.0    3587538.0
1998.0    2785100.0
2002.0    2705197.0
2006.0    3359439.0
2010.0    3178856.0
2014.0    4319243.0
Name: Attendance, dtype: float64

Step 5: Find the average number of goals scored by the home team in each World Cup year.

In [21]:
worldcup.groupby('Year')['Home Team Goals'].mean()

Year
1930.0    3.277778
1934.0    2.823529
1938.0    3.388889
1950.0    3.136364
1954.0    4.192308
1958.0    2.514286
1962.0    2.156250
1966.0    2.156250
1970.0    2.250000
1974.0    1.342105
1978.0    2.078947
1982.0    1.865385
1986.0    1.423077
1990.0    1.288462
1994.0    1.596154
1998.0    1.531250
2002.0    1.390625
2006.0    1.343750
2010.0    1.187500
2014.0    1.237500
Name: Home Team Goals, dtype: float64

Step 6: Find the average number of goals scored by the away team in each World Cup year.

In [22]:
worldcup.groupby('Year')['Away Team Goals'].mean()

Year
1930.0    0.611111
1934.0    1.294118
1938.0    1.277778
1950.0    0.863636
1954.0    1.192308
1958.0    1.085714
1962.0    0.625000
1966.0    0.625000
1970.0    0.718750
1974.0    1.210526
1978.0    0.605263
1982.0    0.942308
1986.0    1.115385
1990.0    0.923077
1994.0    1.115385
1998.0    1.140625
2002.0    1.125000
2006.0    0.953125
2010.0    1.078125
2014.0    1.337500
Name: Away Team Goals, dtype: float64

Step 7: Count the number of matches played in each tournament stage.

In [23]:
worldcup.groupby('Stage')['Stage'].count()

Stage
Final                       20
First round                  9
Group 1                     62
Group 2                     59
Group 3                     56
Group 4                     55
Group 5                      6
Group 6                     12
Group A                     60
Group B                     60
Group C                     48
Group D                     48
Group E                     48
Group F                     48
Group G                     30
Group H                     30
Match for third place       15
Play-off for third place     2
Preliminary round            8
Quarter-finals              66
Round of 16                 72
Semi-finals                 36
Third place                  2
Name: Stage, dtype: int64

Step 8: Count how many matches were played in each host city.

In [24]:
worldcup.groupby('City')['City'].count()

City
Alicante          3
Antibes           1
Arica             7
Barcelona         8
Bari              5
                 ..
Vina Del Mar      8
Washington Dc     5
Yokohama          4
Zaragoza          3
Zurich            5
Name: City, Length: 151, dtype: int64

Step 9: Count the number of matches played in each stadium.

In [25]:
worldcup.groupby('Stadium')['Stadium'].count()

Stadium
Arena Amazonia      4
Arena Fonte Nova    8
Arena Pantanal      4
Arena Pernambuco    6
Arena da Baixada    4
                   ..
Wankdorf Stadium    5
Wembley Stadium     9
Westfalenstadion    4
White City          1
Zentralstadion      5
Name: Stadium, Length: 181, dtype: int64

Step 10. Find the total number of matches officiated by each referee

In [26]:
worldcup.groupby('Referee')['Referee'].count()

Referee
ABD EL FATAH Essam (EGY)           1
ADAIR John (NIR)                   1
AGNOLIN Luigi (ITA)                4
AGUILAR ELIZALDE Abel (MEX)        1
AGUILAR Joel (SLV)                 2
                                  ..
WYSSLING Paul (SUI)                4
Wolfgang STARK (GER)               3
YAMASAKI MALDONADO Arturo (MEX)    5
ZECEVIC Konstantin (YUG)           1
ZSOLT Istvan (HUN)                 5
Name: Referee, Length: 366, dtype: int64

Step 11. Find the number of matches played by each home team.

In [27]:
worldcup.groupby('Home Team Name')['Home Team Name'].count()

Home Team Name
Algeria                        6
Angola                         1
Argentina                     54
Australia                      6
Austria                       13
                              ..
rn">Bosnia and Herzegovina     1
rn">Republic of Ireland        5
rn">Serbia and Montenegro      1
rn">Trinidad and Tobago        1
rn">United Arab Emirates       1
Name: Home Team Name, Length: 78, dtype: int64

Step 12. Find the number of matches played by each away team.

In [28]:
worldcup.groupby('Away Team Name')['Away Team Name'].count()

Away Team Name
Algeria                        8
Angola                         2
Argentina                     27
Australia                      7
Austria                       16
                              ..
rn">Bosnia and Herzegovina     2
rn">Republic of Ireland        8
rn">Serbia and Montenegro      2
rn">Trinidad and Tobago        2
rn">United Arab Emirates       2
Name: Away Team Name, Length: 83, dtype: int64